//! Overlay bank emission (`recompile --bank <name>`).
//!
//! A code overlay is recompiled as a *bank*: the functions inside the shared
//! overlay window, wrapped in `namespace <name>` so banks that reuse the same
//! guest addresses link side by side, plus a self-registering table the
//! runtime consults when the main dispatch misses an address in the window
//! (`psp_overlay_register_bank`, runtime/src/psp_overlay.cpp). The bank is an
//! OBJECT library so its registration object is always linked.

/// Metadata of one overlay bank, emitted into its registration record.
pub struct BankInfo<'a> {
    /// C++ identifier (namespace + CMake target), e.g. "ovAzito".
    pub name: &'a str,
    /// Overlay id from the MWo3 header (word at window base + 4).
    pub id: u32,
    pub window_lo: u32,
    pub window_hi: u32,
    /// Bytes `[window_lo, window_lo + hash_len)` (header + text) are hashed.
    pub hash_len: u32,
    pub hash: u64,
}

/// 64-bit FNV-1a, the same recipe as the runtime's verification.
pub fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in bytes {
        h ^= b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01B3);
    }
    h
}

/// Wrap a generated C++ file in `namespace <name> { ... }`, leaving the
/// leading preprocessor/comment/blank lines (includes, pragma) outside.
pub fn wrap_in_namespace(cpp: &str, name: &str) -> String {
    let mut head = String::new();
    let mut lines = cpp.lines().peekable();
    while let Some(line) = lines.peek() {
        let t = line.trim_start();
        if t.is_empty() || t.starts_with('#') || t.starts_with("//") {
            head.push_str(line);
            head.push('\n');
            lines.next();
        } else {
            break;
        }
    }
    let mut out = head;
    out.push_str(&format!("namespace {name} {{\n"));
    for line in lines {
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(&format!("}} // namespace {name}\n"));
    out
}

/// `bank_dispatch.cpp`: the bank's address -> function table and its
/// static registration with the runtime.
pub fn emit_bank_dispatch(info: &BankInfo, entries: &[(u32, String)]) -> String {
    let n = info.name;
    let mut out = String::new();
    out.push_str("// Generated by psprecomp recompile --bank — do not edit\n");
    out.push_str("#include \"recomp.h\"\n#include \"funcs.h\"\n\n");
    out.push_str(&format!("namespace {n} {{\n"));
    out.push_str("static const uint32_t k_bank_addrs[] = {\n");
    for (addr, _) in entries {
        out.push_str(&format!("    0x{addr:08X}U,\n"));
    }
    if entries.is_empty() {
        out.push_str("    0x00000000U,\n");
    }
    out.push_str("};\nstatic const FuncPtr k_bank_fns[] = {\n");
    for (_, name) in entries {
        out.push_str(&format!("    {name},\n"));
    }
    if entries.is_empty() {
        out.push_str("    nullptr,\n");
    }
    out.push_str("};\n");
    out.push_str(&format!(
        "static const PspOverlayBank k_bank = {{\n    \"{n}\", 0x{id:08X}U, 0x{lo:08X}U, 0x{hi:08X}U,\n    \
         0x{len:08X}U, 0x{hash:016X}ULL,\n    k_bank_addrs, k_bank_fns, {count}U,\n}};\n",
        id = info.id,
        lo = info.window_lo,
        hi = info.window_hi,
        len = info.hash_len,
        hash = info.hash,
        count = entries.len(),
    ));
    out.push_str("static const bool k_bank_registered = (psp_overlay_register_bank(&k_bank), true);\n");
    out.push_str(&format!("}} // namespace {n}\n"));
    out
}

/// `CMakeLists.txt` for a bank: an OBJECT library (so the self-registering
/// object is always linked) named after the bank.
pub fn emit_bank_cmake(name: &str) -> String {
    format!(
        "# Generated by psprecomp recompile --bank — do not edit\n\
         cmake_minimum_required(VERSION 3.20)\n\
         project({name}_bank CXX)\n\n\
         set(CMAKE_CXX_STANDARD 17)\n\
         set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n\
         file(GLOB BANK_SOURCES \"${{CMAKE_CURRENT_SOURCE_DIR}}/generated/batch_*.cpp\")\n\
         list(APPEND BANK_SOURCES\n    \
         \"${{CMAKE_CURRENT_SOURCE_DIR}}/bank_dispatch.cpp\"\n    \
         \"${{CMAKE_CURRENT_SOURCE_DIR}}/mid_entries.cpp\"\n)\n\n\
         add_library({name} OBJECT ${{BANK_SOURCES}})\n\
         target_include_directories({name} PRIVATE\n    \
         \"${{CMAKE_CURRENT_SOURCE_DIR}}/include\"\n    \
         \"${{CMAKE_CURRENT_SOURCE_DIR}}\"\n)\n\
         target_compile_options({name} PRIVATE -O2 -fno-lto -fno-strict-aliasing)\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fnv1a64_known_vectors() {
        assert_eq!(fnv1a64(b""), 0xcbf2_9ce4_8422_2325);
        assert_eq!(fnv1a64(b"a"), 0xaf63_dc4c_8601_ec8c);
    }

    #[test]
    fn wrap_keeps_includes_outside() {
        let cpp = "// gen\n#include \"recomp.h\"\n\nvoid f() {}\n";
        let w = wrap_in_namespace(cpp, "ovAzito");
        let ns = w.find("namespace ovAzito {").unwrap();
        assert!(w.find("#include \"recomp.h\"").unwrap() < ns, "{w}");
        assert!(w.find("void f() {}").unwrap() > ns, "{w}");
        assert!(w.trim_end().ends_with("} // namespace ovAzito"), "{w}");
    }

    #[test]
    fn bank_dispatch_registers_itself() {
        let info = BankInfo {
            name: "ovAzito",
            id: 1,
            window_lo: 0x08ABB180,
            window_hi: 0x08BC6480,
            hash_len: 0x20F3C,
            hash: 0x0123_4567_89AB_CDEF,
        };
        let d = emit_bank_dispatch(&info, &[(0x08ABB1C0, "FUN_08abb1c0".into())]);
        assert!(d.contains("namespace ovAzito {"), "{d}");
        assert!(d.contains("0x08ABB1C0U,"), "{d}");
        assert!(d.contains("    FUN_08abb1c0,"), "{d}");
        assert!(d.contains("\"ovAzito\", 0x00000001U, 0x08ABB180U, 0x08BC6480U"), "{d}");
        assert!(d.contains("0x00020F3CU, 0x0123456789ABCDEFULL"), "{d}");
        assert!(d.contains("psp_overlay_register_bank(&k_bank)"), "{d}");
        assert!(!d.contains("RECOMP_LOOKUP(uint32_t"), "bank must not define RECOMP_LOOKUP");
    }

    #[test]
    fn bank_cmake_is_object_library() {
        let c = emit_bank_cmake("ovAzito");
        assert!(c.contains("add_library(ovAzito OBJECT"), "{c}");
        assert!(!c.contains("psp::recomp"), "{c}");
    }
}
